# Exercise 5: NumPy Array Manipulation

In [1]:
import numpy as np

# Matrix Creation: Create a 5×5 matrix with values from 1 to 25
matrix = np.arange(1, 26).reshape(5, 5)
print("Generated 5x5 Matrix:")
print(matrix)

Generated 5x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [2]:
# Diagonal Extraction: Extract the diagonal elements
diagonal = np.diag(matrix)
print("\nExtracted Diagonal Elements:")
print(diagonal)


Extracted Diagonal Elements:
[ 1  7 13 19 25]


In [3]:
# Calculation: Calculate the sum of the diagonal elements
diagonal_sum = diagonal.sum()
print(f"\nSum of Diagonal Elements: {diagonal_sum}")


Sum of Diagonal Elements: 65
